ALLELE_CUTOFF=$1
PERCENTAGE_CUTOFF=$2
KMERS_OF_INTEREST=$3
TABLE4PLOTTING=$4

module load R
Rscript plot_contingency_tabs.R ${ALLELE_CUTOFF} ${PERCENTAGE_CUTOFF} ${KMERS_OF_INTEREST} ${TABLE4PLOTTING}
